---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: argocd-lab
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: esebogdanolaru/actions-lab1:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
