apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: my-app
spec:
  type: NodePort 
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001 
  selector:
    app: my-app
